export const ADD_INGREDIENTS = 'ADD_INGREDEINTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDEINTS';
export const SET_INGREDIENTS = 'SET_INGREDEINTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';